WITH BSP as (
SELECT b.BOOK_ID, sum(b.PRICE * bs.SALES) as TOTAL_SALES, bs.SALES_DATE, b.AUTHOR_ID, b.CATEGORY
FROM BOOK_SALES as bs
INNER JOIN BOOK as b ON b.BOOK_ID = bs.BOOK_ID 
WHERE YEAR(bs.SALES_DATE) = 2022 and MONTH(bs.SALES_DATE) = 01
GROUP BY b.BOOK_ID)

SELECT a.AUTHOR_ID, a.AUTHOR_NAME, BSP.CATEGORY, sum(TOTAL_SALES) as SALES
FROM BSP
INNER JOIN AUTHOR as a 
ON BSP.AUTHOR_ID = a.AUTHOR_ID 
GROUP BY a.AUTHOR_ID, BSP.CATEGORY
ORDER BY a.AUTHOR_ID ASC, BSP.CATEGORY DESC;
