WITH P_JULY AS (
    SELECT FLAVOR, sum(TOTAL_ORDER) as TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT f.FLAVOR 
FROM FIRST_HALF as f
INNER JOIN P_JULY 
    ON P_JULY.FLAVOR = f.FLAVOR
ORDER BY (f.TOTAL_ORDER + P_JULY.TOTAL_ORDER) DESC
LIMIT 3;