-- 코드를 입력하세요
SELECT u.TITLE, u.BOARD_ID, u_g.REPLY_ID, u_g.WRITER_ID, u_g.CONTENTS, DATE_FORMAT(u_g.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as u
JOIN USED_GOODS_REPLY as u_g ON u.BOARD_ID = u_g.BOARD_ID
WHERE YEAR(u.CREATED_DATE) = 2022 and MONTH(u.CREATED_DATE) = 10
ORDER BY u_g.CREATED_DATE ASC, u.TITLE ASC;